export enum GroupAction {
  CREATE_GROUP = 'CREATE_GROUP',
  GET_GROUP = 'GET_GROUP',
  GET_GROUPS = 'GET_GROUPS',
  SELECT_GROUP = 'SELECT_GROUP',
  JOIN_GROUP = 'JOIN_GROUP',
  LEAVE_GROUP = 'LEAVE_GROUP',
}
